

    # use EKF2 (as of this writing, EKF3 is not supported for handling external navigation data)
    AHRS_EKF_TYPE : 2 # (the default)
    EK2_ENABLE : 1 # (the default)
    EK3_ENABLE : 0 # (the default)
    # disable the GPS
    GPS_TYPE : 0
    # disable the EKF’s use of the GPS
    EK2_GPS_TYPE : 3
    EK2_POSNE_M_NSE : 0.1
    EK2_VELD_M_NSE : 0.1
    EK2_VELNE_M_NSE : 0.1
    MAG_ENABLE : 0
    # disable the EKF’s use of the compass and instead rely on the heading from external navigation data.
    COMPASS_USE : 0
    COMPASS_USE2 : 0
    COMPASS_USE3 : 0 
    # disable EKF Failsafe
    FS_EKF_THRESH : 0
    
